### ISSUE TITLE
Problem lab 3 - Part 2.3: Accessing GitLab (20.20.20.2) as root

### ISSUE THREAD

**Issue by filipposansoldo** [adaltas/ece-devops-2021-fall#2]
Cannot enter at the provided url: [http://20.20.20.2](url) because we do not see the directory `/etc/gitlab/initial_root_password` in our pc. Although we installed `gitlab_server` correctly as from the instructions and we are able to see it running from VirtualBox

**Comment by ThibaultECE** [comment]
Hi,
The directory /etc/gitlab/initial_root_password is hidden but if you type cd /etc it should get you inside otherwise the problem is installation side. 
Hope it will help ^^

**Comment by bloomkail** [comment]
Hi,

You first need to enter the gitlab system using ```vagrant ssh gitlab_server``` (from part-2 directory).

Then, you can interact with the system files of the gitlab server (using ls, cd, cat...)

Hope it helps.

**Comment by filipposansoldo** [comment]
Thank you, I just had to access the virtual machine through `vagrant ssh gitlab_servers` and then look for the repository (`/etc/gitlab/initial_root_password`) there I could see the generated password and login at the address [http://20.20.20.2](url)
