### ISSUE TITLE
installing Docker & WSL2 on Windows breaks VirtualBox 6.1

### ISSUE THREAD

**Issue by Erzangel** [adaltas/ece-devops-2021-fall#3]
Following the Lab guidelines & installing and setting up Docker on Windows while having VirtualBox Ubuntu virtual machines set up on the same environment breaks those virtual machines.

This is apparently caused by WSL2: [See this issue](https://github.com/MicrosoftDocs/WSL/issues/798)

A workaround would be to install Docker in the virtual machines directly, but as we cannot use them because of the Docker Windows installation, it is not a fix if it happened already

**Comment by sergkudinov** [comment]
Thanks for the info. I am closing this issue.
